### ISSUE TITLE
Unable to download images

### ISSUE THREAD

**Issue by priyanka-chaudhary** [cvjena/eu-flood-dataset#1]
Hello,
I wanted to download your image dataset(Images resized to 512 pixels), and it generally starts but fails in few minutes. Would it be possible to check please?
I have tried it 10-15 times and the same thing is happening.

**Comment by Callidior** [comment]
Thanks for your interest in the dataset!
We are hosting the binary files of the dataset on archive.org, which admittedly does not have the fastest connection, but I was able to download the file you mentioned without any problems using my browser within 40 minutes.
However, using a browser for large downloads from archive.org [is generally not recommended][1]. I suggest you try it with a download manager (e.g., `wget` on Unix systems).

To make things a bit easier, I have mirrored this file on another server, which hopefully is faster. You can obtain it [here][2].
I've also added that link as mirror in the README, but I cannot guarantee that the file will stay there forever. Furthermore, that mirror does not have sufficient capacity to host the larger file with the images resized to 1280 pixels; those still have to be obtained from archive.org (using `wget`, preferably).

I hope this helps!
Please let me know if you encounter any other issue.

[1]: https://archive.org/post/1007097/downloading-large-files
[2]: https://cloud.uni-jena.de/index.php/s/Tdns4xnw72XoBiN/download?path=%2F&files=european-flood-2013_imgs_small.zip

**Comment by priyanka-chaudhary** [comment]
@Callidior : Thank you very much. I was able to download using `wget`.
